//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgrajKarte
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public string DateCreated { get; set; }
    
        public virtual LoginSession LoginSession { get; set; }
        public virtual User User { get; set; }
    }
}
