//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgrajKarte
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magarac
    {
        public int Id { get; set; }
        public int User1 { get; set; }
        public int User2 { get; set; }
        public int User3 { get; set; }
        public int User4 { get; set; }
        public int ActiveUser { get; set; }
        public int Status { get; set; }
        public int T2Counter { get; set; }
        public string DateCreated { get; set; }
        public string DateModified { get; set; }
        public string CardsInDeck { get; set; }
    }
}
