//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgrajKarte
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string CardsInHand { get; set; }
        public string CardsOnHeap { get; set; }
        public int Score { get; set; }
        public int Dots { get; set; }
        public int GameType { get; set; }
        public int Win_Loss { get; set; }
        public string DateCreated { get; set; }
        public string DateModified { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> PlayerStatus { get; set; }
    }
}
