//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgrajKarte
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.LoginSessions = new HashSet<LoginSession>();
            this.Logs = new HashSet<Log>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Level { get; set; }
        public string DateCreated { get; set; }
        public string DateModified { get; set; }
        public bool IsSuspended { get; set; }
        public bool IsAutenticated { get; set; }
        public bool IsVerified { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<LoginSession> LoginSessions { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
    }
}
